### ISSUE TITLE
Calculating energies for S66

### ISSUE THREAD

**Issue by jthorton** [rinikerlab/ANA2B#1]
Hi thanks for making these models open source!

I am interested in calculating the energy components predicted by this model using the HybridFF ase calculator and the `get_components` method for dimers from the S66 dataset. In testing, this works fine when the monomers are the same but gives strange results when they are different due to how the HybridFF calculator is set up. Would it be possible to give an example of how to calculate the breakdown for these cases?

**Comment by moritztdev** [comment]
Hey, thanks for your interest. 

Yes, as you correctly noticed, the HybridFF calculator is currently built around the assumption that the system consists of a single molecule. This will probably not change anytime soon.

However, I've added an example in [source/examples/](https://github.com/rinikerlab/ANA2B/blob/main/source/examples/example_dimer.ipynb) that shows how you can put together the different modules to calculate the components of a dimer with two different monomers (example S66x8).

Hope it helps.

**Comment by jthorton** [comment]
Hi @MOSNPDEV, thanks very much for the example that worked perfectly! Thanks again for making this all open source!
